spring.application.name=Security
server.port=8080

spring.config.activate.on-profile=prod

logging.level.org.springframework.security=ERROR

spring.security.user.name=user
spring.security.user.password=Test@Security_123456

# Database URL (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security
# Database username
spring.datasource.username=postgres
# Database password
spring.datasource.password=hggi
# Database driver (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver

# Specify the Hibernate dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Automatically update schema based on entity changes (Options: none, validate, update, create, create-drop)
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in the console
spring.jpa.show-sql=false
# Pretty-print SQL output for better readability
spring.jpa.properties.hibernate.format_sql=false
# Define default schema
spring.jpa.properties.hibernate.default_schema=public
# Disable Open Session in View to avoid lazy loading issues
spring.jpa.open-in-view=false